function [F,H] = jacobiani_analitici(alpha,alpha_dot,beta,beta_dot,F1,F2,dt,rho,m,l,g,J_y,J_z,I_b,J_alpha,c_alpha,c_beta,eps_p,eps_y,Cd_A_x,Cd_A_y,Cd_A_z)
%JACOBIANI_ANALITICI
%    [F,H] = JACOBIANI_ANALITICI(ALPHA,ALPHA_DOT,BETA,BETA_DOT,F1,F2,DT,RHO,M,L,G,J_y,J_z,I_b,J_alpha,C_ALPHA,C_BETA,EPS_P,EPS_Y,Cd_A_x,Cd_A_y,Cd_A_z)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    30-Jun-2026 19:07:32

t2 = cos(alpha);
t3 = cos(beta);
t4 = sin(alpha);
t5 = sin(beta);
t6 = alpha_dot.^2;
t7 = beta_dot.^2;
t8 = l.^2;
t12 = 1.0./J_alpha;
t9 = t8.^2;
t10 = t2.^2;
t11 = t4.^2;
t13 = m.*t8;
t16 = t6.*t8;
t14 = J_y.*t11;
t15 = J_z+t13;
t17 = t7.*t8.*t10;
t18 = t10.*t15;
t21 = t16+t17+1.0e-5;
t19 = I_b+t14+t18;
t22 = sqrt(t21);
t20 = 1.0./t19;
t23 = 1.0./t22;
mt1 = [1.0,-dt.*t12.*(g.*l.*m.*t2-(Cd_A_z.*alpha_dot.*rho.*t2.*t4.*t7.*t9.*t23)./2.0),0.0,dt.*t20.*(-F2.*l.*t4+F1.*eps_y.*l.*t2+(Cd_A_y.*beta_dot.*rho.*t4.*t8.*t22)./2.0+(Cd_A_y.*beta_dot.^3.*rho.*t4.*t9.*t10.*t23)./2.0)+dt.*t20.^2.*(J_y.*t2.*t4.*2.0-t2.*t4.*t15.*2.0).*(beta_dot.*c_beta-F2.*l.*t2-F1.*eps_y.*l.*t4+(Cd_A_y.*beta_dot.*rho.*t2.*t8.*t22)./2.0),dt,-dt.*t12.*(c_alpha+(Cd_A_z.*rho.*t8.*t22)./2.0+(Cd_A_z.*rho.*t6.*t9.*t23)./2.0)+1.0,0.0,Cd_A_y.*alpha_dot.*beta_dot.*dt.*rho.*t2.*t9.*t20.*t23.*(-1.0./2.0),0.0,-dt.*t12.*(F1.*l.*t5-F2.*eps_p.*l.*t3),1.0,0.0,0.0,Cd_A_z.*alpha_dot.*beta_dot.*dt.*rho.*t9.*t10.*t12.*t23.*(-1.0./2.0),dt];
mt2 = [-dt.*t20.*(c_beta+(Cd_A_y.*rho.*t2.*t8.*t22)./2.0+(Cd_A_y.*rho.*t2.^3.*t7.*t9.*t23)./2.0)+1.0];
F = reshape([mt1,mt2],4,4);
if nargout > 1
    H = reshape([-g.*t2,-t4.*t5,0.0,0.0,0.0,t2.*t3,0.0,0.0],[2,4]);
end
end
